### ISSUE TITLE
Can't install on windows 8.1.

### ISSUE THREAD

**Issue by AngheloAlf** [mjpizz/skyper#1]
Trying to install skyper, but npm says "virtualenv-postinstall" fails.

Including the log file.

Haven't tried on other OS

[npm-debug.log.txt](https://github.com/mjpizz/skyper/files/562813/npm-debug.log.txt)

**Comment by mjpizz** [comment]
hi there! thanks for the debug log. I took a look and I can't see anything obvious pointing to the root cause. Unfortunately, I don't have Windows 8.1 to reproduce, but will keep an eye out if anyone else runs into this

**Comment by adminy** [comment]
I did windows 10 :)  basically same error ...
